### ISSUE TITLE
[ZS] Add other effects to prop_baseoutlined

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#11]
Allow switching between effects for prop_baseoutlined.
Add a dropdown menu with options to change the effect.

- Default
- Cheap
- Halo
- Solid wireframe
- Static light trail
- Painted
- Disabled

Add any other types of effects.

**Comment by sunrust-serv** [comment]
what's cheap?

**Comment by besenyei** [comment]
Cheap is already in the gamemode and is applied when the client doesn't support shader model 2.

Static light trail is a short beam of sorts which originates from the model.
Example from Borderlands.
https://vignette.wikia.nocookie.net/borderlands/images/a/a7/Borderlands-2-Weapons.jpg/revision/latest?cb=20121112151444

Painted is a simple color overlay on the model.

**Comment by sunrust-serv** [comment]
Oh, I remember making static light trail a long time ago, I'll try finding that code

**Comment by besenyei** [comment]
> [sunrust-zs:master] 1 new commit 717999b 
Added 2 new options - enable dropped item beams and drop down for choosing how dropped items render
