### ISSUE TITLE
[ZS] Add options to toggle font outlines, shadows, and transparent hud areas

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#19]
Add options to toggle:

- [ ] Font shadows
- [ ] Font outlines
- [ ] hud fill areas
- [ ] ~fear-o-meter~ (old)

-----------------------------------------------------------------------

### Health bar

I didn't want to make another suggestion/issue for this.

The health display should not be drawn at all for 0 hp.

**Comment by besenyei** [comment]
Could you benchmark the fps perf from the above, and only add options to toggle what ever made an impact.

**Comment by Raox2** [comment]
Closed. Font glows/shadows can be disabled, outlines are just part of the font, hud fill areas won't do much.
