### ISSUE TITLE
[ZS] Destroy certain projectiles on hit from world/prop collision

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#21]
Edited suggestion after the reply.

### Arrows

Only after the arrow performs damage against the enemy, that it should be considered for removal on world/prop collision.

- projectile_arrow_inq - Inquisitor
- projectile_arrow - Impaler

----------------------------------------------------------------------------------------

### ~~Darts~~

~~When darts collide with the world/props, they should be destroyed.~~

**Comment by sunrust-serv** [comment]
The Impaler keeps doing damage even at minimum damage. This would only apply to the Inquisitor.

**Comment by besenyei** [comment]
I'd choose the second suggestion to apply for both.
Only destroy the projectile on collision with the world after it's done the damage.

**Comment by besenyei** [comment]
> [sunrust-zs:master] 1 new commit
> 8af38a6 Various optimisations/cosmetic changes
> Med darts no longer linger and are immediately removed on contact

**Comment by besenyei** [comment]
> [sunrust-zs:master] 1 new commit
> 8fb7db5 Remove impaler/inquisitor bolts from world once... - Raox2
