### ISSUE TITLE
[ZS] Split status_human_holding into server and client realm

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#28]
### Client

- Hide the serverside model for the local player, and create a clientsided model.

- Rotation is handled clientside by the prop holder.

### Server

- Rotation position from the client owner is updated at a rate suitable for the server's current tickrate.

- At a distance, lower this update rate for other players.

- Interpolate the serverside rotation, so that it looks smooth for other players, and increase it when the update rate is lower.

--------------------------------------------------------------------------------------

If such a change was made, it would end cading woes in general, especially for high ping players.
Everyone would benefit from the rotation responsiveness as it mimics that of singleplayer mode.

I understand that the changes this suggestion seeks are more involved, which is why no one has done it yet.

**Comment by Raox2** [comment]
super tricky to do

**Comment by besenyei** [comment]
If interpolation will cause that, then it's not necessary.

Changes in status_human_holding has to look the same as it's always been serverside, 
while the real magic takes place clientside.

**Comment by Raox2** [comment]
If the client predicts it wrong then it would have to rereplicate it. I suppose it is possible with DTAngs/Vecs

**Comment by besenyei** [comment]
I think it would also be better to simulate the rotation from the physgun.
http://wiki.garrysmod.com/page/Entity/StartMotionController

**Comment by Raox2** [comment]
Rotation has been reworked.
