### ISSUE TITLE
[ZS] Make voicesets entirely clientside

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#34]
https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/gamemode/init.lua#L516-L521

```lua
	util.AddNetworkString("voice_eyepain")
	util.AddNetworkString("voice_giveammo")
	util.AddNetworkString("voice_death")
	util.AddNetworkString("voice_zombiedeath")
	util.AddNetworkString("voice_pain")
	util.AddNetworkString("voice_zombiepain")
```

--------------------------------------------------------------------------------

Make certain voices restricted to players that interact with each other, such as voice_giveammo.

**Comment by Raox2** [comment]
They have to be broadcast to all players in some way.

**Comment by besenyei** [comment]
Would it be possible to just tie them to the event they're intended for, and not have to broadcast them separately?

**Comment by Raox2** [comment]
That would be then broadcasting ammo receive events to more players for
example. This is only worthwhile if the net messages already send the
entities.

**Comment by besenyei** [comment]
Is there a tangible method of detecting the event from the client, and only having voicesets play for the clients that witness the event?

**Comment by Raox2** [comment]
Pain sounds have been optimised via NW2Vars
