### ISSUE TITLE
[ZS] Change zombie vision rendering of humans

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#35]
Instead of their entire model colored with their health state, change it to a halo effect, only render the halo outline through walls.

----------------------------------------

Make it an option if necessary.

**Comment by Raox2** [comment]
Halos are expensive in lua

**Comment by besenyei** [comment]
Is that after render.supressenginelighting is true?

**Comment by Raox2** [comment]
I don't know, but I know the effect is expensive.

**Comment by besenyei** [comment]
https://github.com/Facepunch/garrysmod/pull/1113

I'd give it a go, and if it happens to be more expensive than the previous one, then I'll close this suggestion.

**Comment by besenyei** [comment]
Did my own test, they are expensive, but it looks like the cause is due to a bug, every time I had 4 players with the halos drawn on them, it would cause Mat_ThreadedEndFrame to spike a lot.

Disabling mcore, shows that Swap Buffers, GMOD and GLua are affected.
Removing the entities or the halos themselves, does not cut down the cost, only a changelevel fixes that.

I'll probably re-open this if those bugs are fixed.
