### ISSUE TITLE
[ZS] Add tab "Performance" in options

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#4]
Most of the time, players don't actually know there are ways to improve their fps, by toggling commands in the game's console.
Most just accept nothing can be done to improve client performance on their end.

I would like to see various commands which improve performance be included in a nice and convenient place, instead of having to search them up on the internet, steam guides, gmod update logs or asking around.

Engine commands such as:
- gmod_mcore_test 1
- cl_threaded_bone_setup 1
- r_drawdetailprops 0
- cl_show_splashes 0 (disables splash effects when shooting water, can get really expensive when multiple players/turrets are firing)
- [r_drawwaterreflection 0](https://github.com/Facepunch/garrysmod-issues/issues/3475) (prevents re-rendering the world)
- r_flashlightdepthtexture 0 (disables flashlight models, causes freeze on toggle)
- r_drawflecks 0 (disables flecks created from bullets impacting surface type)

Include any I've missed.
I use more than the ones listed above, some may be placebo.

Move certain gamemode commands to this tab:

- zs_fonteffects 0
- zs_filmmode 1
- zs_messagebeaconshow 0
- zs_transparencyradius
- zs_transparencyradius3p
- zs_alwaysshownails 0

Include any I've missed.

Over time it would be great if more options were added to lower performance overhead from the gamemode, as some things can't be toggled in the engine without the use of sv_cheats or they simply don't exist at all.

**Comment by ritzbits** [comment]
On the topic of performance, HG apparently has a collision fix of some kind that seems to improve fps by quite a bit, although I don't know any specifics about it.

**Comment by besenyei** [comment]
I think that's probably got nothing to do with client performance, but rather server performance.
https://github.com/Facepunch/garrysmod-issues/issues/3082

**Comment by besenyei** [comment]
r_eyemove 0 - disables eye movement (players eyes aim at the closest player)
blink_duration 0 - how many seconds an eye blink will last.
r_flex 0 - disables facial expressions (unsure if this is necessary since mouthmoveanims are disabled)

In my current config these didn't really affect fps, may be helpful for others though.

**Comment by besenyei** [comment]
I looked at cl_show_splashes 0 again with cl_particle_show_bbox 1, it seems to only toggle the rendering of it, it doesn't actually disable it.

I believe disabling [this](https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/gamemode/obj_entity_extend.lua#L44) would be better.
