### ISSUE TITLE
[ZS] Smart Targeting locked-on player visual indicator

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-suggestions#49]
When smart targeting locks-on to a player, a green arrow indicator appears above their head.

Has same appearance as the Aim Compensator indicator when crosshair is over a target. However, the green arrow will always stay above their head as long as that player is locked-on to.

**Comment by ritzbits** [comment]
[sunrust-zs:master] 1 new commit
5375e62 Reduced velocity of medic rifle darts to make them less buggy when locked on
Locked on players using Smart Targetting now have an indicator above their head

**Comment by ritzbits** [comment]
Issue: arrow indicator does not pop up on smart targeting lock of a player, requires switching to another weapon and back to the dart gun.

**Comment by Raox2** [comment]
The delay is for performance reasons, I'm afraid

**Comment by Raox2** [comment]
It might be better now? Tell me how it is.

**Comment by ritzbits** [comment]
The delay reduction to 1 second works well. Not sure if the arrow indicator was usable with buff-type dart weapons so left this open.
