### ISSUE TITLE
[ZS/Sparkwerk] logic_experience map message

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-suggestions#50]
logic_experience is a rarely used entity but it could use a map message indicating an experience multiplier is present, similar to the message that appears on difficult/low-winrate maps regarding additional ember/XP rewards.

**Comment by besenyei** [comment]
If this isn't already implemented it should be, it could be a message that appears in both chatbox and center hud message when wave 1 starts.

**Comment by ritzbits** [comment]
changed my mind seeing as a map could print it manually; although it would be missing the nice green colour
