### ISSUE TITLE
[ZS] Barricading changes / reduce nail health per repair

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-suggestions#52]
```
GM.NailHealthPerRepair = 11.7--CreateConVar("zs_nailhealthperrepair", "10", FCVAR_ARCHIVE + FCVAR_NOTIFY, "How much health a nail gets when being repaired."):GetInt()
-- cvars.AddChangeCallback("zs_nailhealthperrepair", function(cvar, oldvalue, newvalue)
-- 	GAMEMODE.NailHealthPerRepair = tonumber(newvalue) or 1
-- end)
```

Not sure when this was upped from 10 -> 11.7, although this change came before the introduction of points/XP awarded for barricading. It's my understanding this increase was to address the difficulty of gaining points while barricading because repairing was previously the only method to gain points using a Carpenter's Hammer.

With the introduction of the points/XP award system players with carpenter's hammers now have viable methods of gaining moderate amounts of points, and this is stackable with repairing. With the ability to craft the electrohammer, upgrade the carpenter's hammer, use Handy I-IV skills (+20% repair rate) and Hammer Discipline, and acquire blueprint trinkets, the repair capability of a single player.

- Reduce nail health per repair from 11.7 back to 10
Reducing the nail health repaired per hit from 11.7 to 10 helps to reduce the feasibility of solo cading where players create layered barricades and repair them. Since players are able to repair quickly for high amounts of nail health, zombies won't be able to quickly break props in solo cades as the health repaired per second may match or be close enough to damage per second by zombies.

It's my understanding one of the reasons the sigil fragment was removed from the worth menu was because of players would check them out to create solo barricades and teleport out as they fell. One of the reasons solo barricading may still remain viable is because they can be maintained for long periods of time, allowing sigil fragment purchases from the points shop.

1.7 in repair value is a small change but it would help counterbalance the buffs to barricading since the skill and sigil update, which includes the +1.7 increase from 10. This change is not directly meant to address solo barricades but would help to reduce the ability of (solo) barricades to be maintained by one person among other things.

---

The nail health per repair change was the main suggestion for this issue, although if additional changes to barricading is warranted, given the points/XP award system on top of repair points, then it may be discussed here.

**Comment by ritzbits** [comment]
Given the reductions to points/XP awarded from barricades in earlier waves, it looks like less points are gained from that system through solo cading with a good amount coming from repair points.

**Comment by Raox2** [comment]
Was reduced because the skills give less repair value

**Comment by Raox2** [comment]
Feel like nerfing this might nerf legit cades too hard

**Comment by ritzbits** [comment]
To address the concern about legit cades, it might be worth redistributing the loss of repair capability (-1.7) to the repair field emitter/nanite cloud bomb, and possibly the advanced blueprints trinket.

Revised suggestion:

- Reduce nail health per repair from 11.7 back to 10
- Increase repair field emitter nail health per burst from 8 to 9/10
- Nanite cloud bombs reinforce barricades (-10% damage) for props within their radius for as long until their active duration

Other possible changes:
- Increase advanced blueprints repair rate increase from 20% to 25%

These changes are oriented towards reducing the ability of (solo) barricades to be maintained by one person. With these changes, legit cades shouldn't have too much trouble as long as they have support players using nanite cloud bombs/repair field emitters alongside players with carpenter's hammers.

These changes are partially meant to address:

1. solo barricades, among other things, by reallocating repair capability to other barricade tools: one player shouldn't be able to check out a carpenter's hammer, electrohammer, and repair field emitter since they won't have enough worth. They'll still be able to upgrade their hammer but relying solely on just the hammer for repair will reduce their rate of repair capability.

2. the repair field emitter consumes quite more pulse ammo than other pulse deployables such as the zapper and force field emitter, it already may be an easy way to gain points, although it's worth value is 50 compared to the FF emitter at 35; and points may not come in until later waves.

3. the nanite cloud bomb's nanites act to reinforce barricades in addition to repairing them: this should increase the utility of the nanite cloud bomb and more players may check them out (currently don't have statistics on worth menu checkouts)..

`4. increasing the advanced blueprints repair rate from 20% to 25% still lets barricaders have a high rate of repair, but this moves higher repair rates to being more accessible in later waves and less accessible in early waves for solo barricading.
