### ISSUE TITLE
[Sparkwerk] Change bot joining message

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#53]
> [botname] has joined
> Everybody welcome [botname] ...

Could this be changed to the following:

> A bot has joined the game.

or

> Bot count increased to n.

**Comment by Raox2** [comment]
I actually kinda want to hide it

**Comment by besenyei** [comment]
Good enough.

**Comment by besenyei** [comment]
```
[sparkwerk:master] 1 new commit
2756509 Bots don't show join or welcome messages - Raox2
```
