### ISSUE TITLE
[ZS] Scraps that are made in remantler message merge.

### ISSUE THREAD

**Issue by IAmSorre** [Raox2/sunrust-suggestions#62]
Like the healing message, it should merge. Seeing that the message spam when someone uses my remantler and notify multiple times that scrap has been made. 

Edit: do the same for resupplies.

**Comment by ritzbits** [comment]
Raox2
[sunrust-zs:master] 1 new commit
8406a24 Scrap creation and ammo pickup messages are now... - Raox2
