### ISSUE TITLE
[ZS] func_status entity update

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-suggestions#67]
func_status takes in a string as an argument but new statuses (new debuffs, buffs) can't be selected otherwise it will default to debuff_slow since they are recognized as invalid. It could be updated to accept any status name since there are more now, and because they might change in the future.

``` elseif key == "status" then
		local val = string.lower(value)
		self.Status = (val == "debuff_slow" or val == "debuff_dimvision" or val == "debuff_enfeeble" or val == "debuff_frost") and val or "debuff_slow"```

**Comment by Raox2** [comment]
👍
