### ISSUE TITLE
[ZS] Specify team in transmit state of some entities

### ISSUE THREAD

**Issue by besenyei** [Raox2/sunrust-suggestions#7]
[TRANSMIT_ALWAYS](https://github.com/JetBoom/zombiesurvival/search?q=TRANSMIT_ALWAYS&unscoped_q=TRANSMIT_ALWAYS)

Zombie team:
- prop_creepernest - TRANSMIT_PVS for the Human team.
- prop_thrownbaby - same
- point_worldhint (zombie) - TRANSMIT_NONE for the Human team.

Human team:
- prop_messagebeacon
- point_worldhint (human) - TRANSMIT_NONE for the Zombie team.

The ones not listed, are fine as they are.

**Comment by Raox2** [comment]
Can't be done

**Comment by sunrust-serv** [comment]
It's totally serverside

**Comment by besenyei** [comment]
I don't know if what I'm saying is entirely correct, but wouldn't you just do entity:SetPreventTransmit( ply, true ), or return a different transmit state for the player, based on team?
https://wiki.garrysmod.com/page/Controlling_Entity_Transmission

**Comment by sunrust-serv** [comment]
In that case, yes

**Comment by sunrust-serv** [comment]
Ah, that function will filter it even if you can see the entity.

**Comment by besenyei** [comment]
Could the entities (or their models) themselves be prevented from drawing outside of pvs, while still transmitting their required states?

**Comment by besenyei** [comment]
Maybe when this becomes a possibility it should be considered, for now I'll close it.
