### ISSUE TITLE
[ZS] prop_invitem entity keyvalues and input

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-suggestions#70]
Request

```function ENT:SetInventoryItemType(type, level)```

prop_invitem has a keyvalue to set the inventory item type (pass string to the type argument), although there is no way to set the level argument.

* Add keyvalue to set item level.
* Add two inputs to set inventory item type, and level.
e.g.
``    elseif name == "setinvitemtype" then
        SetInventoryItemType(arg)```

**Comment by Raox2** [comment]
👍
