### ISSUE TITLE
[ZS] Map current time elapsed on scoreboard

### ISSUE THREAD

**Issue by ritzbits** [Raox2/sunrust-suggestions#73]
Displays current time elapsed on map on scoreboard. Round restarts will not reset this timer, mirroring the same message printed in #game-servers-info for objective maps (played for 25.04 minutes). Useful for gauging whether or not if a round is eligible for replay, and if it is the second round.

**Comment by Raox2** [comment]
👍

**Comment by ritzbits** [comment]
Raox2
[sunrust-zs:master] 1 new commit
0069cef Added the synced round time to the scoreboard, ... - Raox2
